In [1]:
import pandas as pd
import numpy as np

df = pd.read_csv('라벨붙임.csv',encoding='cp949')
df = df.drop('Unnamed: 0',axis=1)
df

,고객번호,A_구매금액,기타CV_S,식료품_NET,의류_NET,생활_NET,RFM등급,휴일_CV_S,편의품_CV_S,선매품CV_S,객단가증감률,B_구매금액,C_구매금액,kmeans_label
0,1,1.367753,-0.840909,-0.144455,0.238970,-3.296500,-1.739425,-0.015794,0.382423,-0.803469,-0.912943,-0.214188,-0.135190,2
1,2,1.776146,0.201445,-0.144455,1.282634,-0.051626,-0.792279,-0.488643,0.298866,-0.848143,-0.912943,-0.234609,-0.205711,2
2,3,-0.496782,-1.569289,-0.144455,0.238970,-0.051626,-0.034562,0.466305,0.071407,2.538651,-0.203346,-0.242069,0.018349,0
3,4,-0.170812,-0.657451,-0.144455,0.238970,-0.862844,1.291443,0.288886,-0.329763,-0.532511,-0.912943,-0.181465,-0.146886,1
4,10,-0.400193,-0.190214,-0.144455,0.238970,-0.051626,-0.981708,-1.060247,-1.245738,-0.327869,-0.203346,-0.145213,0.632941,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10743,19325,-0.207098,0.126255,-0.144455,0.238970,-0.862844,0.723155,0.657320,1.350886,0.234927,0.506252,-0.222418,-0.205096,2
10744,19327,-0.498162,2.347770,-0.144455,1.282634,-0.051626,-0.413420,-0.014097,0.781941,2.607661,-0.912943,-0.239206,0.324242,0
10745,19332,-0.493328,2.347770,0.854647,1.282634,-0.051626,0.533726,0.430470,0.248380,1.333528,1.215849,-0.234873,0.748546,0
10746,19333,-0.438943,-0.713786,-0.144455,-0.804693,-0.862844,1.291443,-0.587946,0.875390,1.377105,-0.912943,-0.202690,-0.203839,0
10747,19334,-0.488963,0.055907,-1.143558,1.282634,-0.051626,-1.360567,0.129032,1.695419,0.715794,-2.332137,0.178407,-0.148936,2

In [2]:
df1 = df[df['kmeans_label']==0] # 1번군집
df2 = df[df['kmeans_label']==1] # 2번군집
df3 = df[df['kmeans_label']==2] # 3번군집
df1 = df1[['고객번호']]
df2 = df2[['고객번호']]
df3 = df3[['고객번호']]

In [2]:
# 소분류,고객번호 테이블을 불러옴
a = pd.read_csv('test21.csv',encoding='cp949')

In [12]:
# 1번군집 + 소분류
b = pd.merge(df1,a,on='고객번호',how='left')

In [8]:
# 2번군집 + 소분류
c = pd.merge(df2,a,on='고객번호',how='left')

In [14]:
# 3번군집 + 소분류
d = pd.merge(df3,a,on='고객번호',how='left')

In [15]:
import csv
b.to_csv('1번군집.csv',mode="w",encoding='euc-kr',index=False)

In [ ]:
import csv
c.to_csv('2번군집.csv',mode="w",encoding='euc-kr',index=False)

In [16]:
import csv
d.to_csv('3번군집.csv',mode="w",encoding='euc-kr',index=False)