In [19]:
import pandas as pd
import numpy as np

In [20]:
prod = pd.read_csv('./data/PRODCL2.csv')
prod

     제휴사  대분류코드  중분류코드    소분류코드    중분류명      소분류명  상품분류 소비재분류
0      A      1    101  A010101    일용잡화      위생세제  생활잡화   편의품
1      A      1    101  A010102    일용잡화       휴지류  생활잡화   편의품
2      A      1    101  A010103    일용잡화      뷰티상품  생활잡화   편의품
3      A      1    101  A010104    일용잡화      일용잡화  생활잡화   편의품
4      A      1    101  A010105    일용잡화      세트상품  생활잡화   편의품
...   ..    ...    ...      ...     ...       ...   ...   ...
4381   D      8    802  D080204  아이메이크업     아이섀도우   화장품   편의품
4382   D      8    802  D080205  아이메이크업    메이크업세트   화장품   편의품
4383   D      8    803  D080301   립메이크업  립스틱/립라이너   화장품   편의품
4384   D      8    803  D080302   립메이크업   립글로즈/틴트   화장품   편의품
4385   D      8    804  D080401  네일메이크업  일반네일/케어류   화장품   편의품

[4386 rows x 8 columns]

In [21]:
prod1 = prod[['소분류명','소비재분류']]
prod1.columns =['품목명','소비재분류']

In [22]:
g1 = pd.read_csv('./data/1번군집.csv',encoding='cp949')
g1 = g1.set_index('고객번호')
g2 = pd.read_csv('./data/2번군집.csv',encoding='cp949')
g2 = g2.set_index('고객번호')
g3 = pd.read_csv('./data/3번군집.csv',encoding='cp949')
g3 = g3.set_index('고객번호')

In [23]:
prod_col1 = prod.loc[prod['소비재분류']=='편의품']['소분류명'].values
g1_col = np.array(g1.columns.to_list()) 
ili1 = np.where(np.isin(g1_col, prod_col1)==True)[0]
g1 = g1[g1_col[ili1]]
g1

,2단우산,3단우산,3분요리류,BB/파운데이션/컴팩트류,DIY소가구,DIY완구,DVD,Digital Accessory,FAST FOOD,GAP감귤,...,훼이셜스킨케어,훼이셜클렌저,훼이셜클린져,휴대폰기타용품,휴모니아,휴지류,휴지통,흑미,흑미류,흰다리새우
고객번호,,,,,,,,,,,,,,,,,,,,,
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
28,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
33,0.0,0.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
43,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19309,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
19320,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5.0
19327,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
19332,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
19333,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [24]:
prod_col2 = prod.loc[(prod['소비재분류']=='전문품') | (prod['소비재분류']=='선매품')]['소분류명'].values
g2_col = np.array(g2.columns.to_list()) 
ili2 = np.where(np.isin(g2_col, prod_col2)==True)[0]
g2 = g2[g2_col[ili2]]
g2

,14K,ACC Bloom (1F),ACC Bloom (3F),AK골프,ANDZ,ARCHIV,BON,Bag&Bag,DIY가전,DKNY,...,황기,황토침구,휘트니스,휠라골프,휠라아웃도어,휴고보스,휴고보스골프,히터,히터기,힐앤토트
고객번호,,,,,,,,,,,,,,,,,,,,,
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
14,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
15,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19293,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
19301,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
19310,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
19311,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
19322,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [25]:
prod_col3 = prod.loc[prod['소비재분류']=='선매품']['소분류명'].values
g3_col = np.array(g3.columns.to_list()) 
ili3 = np.where(np.isin(g3_col, prod_col3)==True)[0]
g3 = g3[g3_col[ili3]]
g3

,14K,ACC Bloom (1F),ACC Bloom (3F),AK골프,ANDZ,ARCHIV,BON,Bag&Bag,DIY가전,DKNY,...,화장품,황기,황토침구,휘트니스,휠라골프,휠라아웃도어,휴고보스,휴고보스골프,히터,히터기
고객번호,,,,,,,,,,,,,,,,,,,,,
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
17,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
18,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
19,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19298,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
19304,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
19314,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
19325,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
19334,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [26]:
g12 = pd.concat([g1,g2])
ga = pd.concat([g12,g3])
ga.fillna(0,inplace=True)
ga

,2단우산,3단우산,3분요리류,BB/파운데이션/컴팩트류,DIY소가구,DIY완구,DVD,Digital Accessory,FAST FOOD,GAP감귤,...,황기,황토침구,휘트니스,휠라골프,휠라아웃도어,휴고보스,휴고보스골프,히터,히터기,힐앤토트
고객번호,,,,,,,,,,,,,,,,,,,,,
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
28,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
33,0.0,0.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
43,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19298,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
19304,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
19314,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
19325,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
19334,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [27]:
# 코사인 유사도를 하기 위해서 전치 행렬을 구하는 단계 
ga_T = ga.transpose()
ga_T

고객번호,3,12,28,33,43,55,57,64,71,98,...,19279,19280,19282,19290,19297,19298,19304,19314,19325,19334
2단우산,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3단우산,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3분요리류,0.0,0.0,0.0,4.0,1.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
BB/파운데이션/컴팩트류,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
DIY소가구,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
휴고보스,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
휴고보스골프,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
히터,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
히터기,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
힐앤토트,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [28]:
from sklearn.metrics.pairwise import cosine_similarity

item_sim = cosine_similarity(ga_T,ga_T)
# 코사인 유사도 만든 행렬을 데이터프레임으로 변환 
item_sim_df = pd.DataFrame(data=item_sim, index = ga.columns,
                          columns=ga.columns)
print(item_sim_df.shape)
item_sim_df.head(3)

(3399, 3399)

,2단우산,3단우산,3분요리류,BB/파운데이션/컴팩트류,DIY소가구,DIY완구,DVD,Digital Accessory,FAST FOOD,GAP감귤,...,황기,황토침구,휘트니스,휠라골프,휠라아웃도어,휴고보스,휴고보스골프,히터,히터기,힐앤토트
2단우산,1.000000,0.057061,0.008905,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3단우산,0.057061,1.000000,0.004287,0.014900,0.000000,0.0,0.000000,0.000000,0.004823,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3분요리류,0.008905,0.004287,1.000000,0.012498,0.004722,0.0,0.014842,0.029264,0.023706,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [29]:
# 코사인유사도 내적곱한값을 코사인 유사도 절대값의 합으로 나눈 거(정규화를위해서)
import numpy as np
def predict_ga(ga_arr, item_sim_arr):
    ga_pred = ga_arr.dot(item_sim_arr)/np.array([np.abs(item_sim_arr).sum(axis=1)])
    return ga_pred

In [30]:
# 개인별 상품 예측 
ga_pred = predict_ga(ga.values, item_sim_df.values)
ga_pred_matrix = pd.DataFrame(data=ga_pred, index = ga.index,\
                            columns = ga.columns)
ga_pred_matrix

C:\Users\danie\AppData\Local\Temp/ipykernel_5744/2520657378.py:4: RuntimeWarning: invalid value encountered in true_divide
  ga_pred = ga_arr.dot(item_sim_arr)/np.array([np.abs(item_sim_arr).sum(axis=1)])

,2단우산,3단우산,3분요리류,BB/파운데이션/컴팩트류,DIY소가구,DIY완구,DVD,Digital Accessory,FAST FOOD,GAP감귤,...,황기,황토침구,휘트니스,휠라골프,휠라아웃도어,휴고보스,휴고보스골프,히터,히터기,힐앤토트
고객번호,,,,,,,,,,,,,,,,,,,,,
3,1.440462,1.638531,0.290911,0.303330,0.141377,1.254548,0.075472,0.122039,0.189310,NaN,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,0.000000
12,0.273460,0.301242,0.356108,0.213559,0.317300,0.200684,0.142394,0.324330,0.271595,NaN,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,0.000000
28,0.854942,0.876489,1.404688,0.365388,0.959163,0.721926,0.669524,1.198546,1.034451,NaN,...,0.009832,0.014549,0.001843,0.002100,0.000000,0.000000,0.000000,0.001328,NaN,0.000542
33,1.257465,1.187232,2.153425,0.522289,1.280276,1.054104,0.945467,1.650358,1.500971,NaN,...,0.006247,0.011344,0.004535,0.002906,0.002083,0.004176,0.013189,0.003115,NaN,0.003605
43,0.722105,0.710693,1.139129,0.268775,0.824241,0.733321,0.582089,0.911688,0.818964,NaN,...,0.006445,0.007162,0.002682,0.001163,0.000833,0.001671,0.005276,0.001246,NaN,0.001442
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19298,0.000610,0.000976,0.002090,0.000609,0.004692,0.000607,0.037696,0.000868,0.001154,NaN,...,0.227366,0.157515,0.449565,0.815604,0.476435,0.614483,0.366984,0.474979,NaN,0.337761
19304,0.000036,0.000357,0.000138,0.000210,0.002558,0.000223,0.072581,0.000000,0.000061,NaN,...,0.306277,0.216372,0.732877,0.739416,0.609688,0.782406,0.681234,0.175447,NaN,0.657978
19314,0.000012,0.000150,0.000107,0.000098,0.000853,0.000177,0.107101,0.000078,0.000056,NaN,...,0.247534,0.226705,0.957085,0.940191,0.642467,1.455818,1.501692,0.162211,NaN,1.348056
19325,0.000000,0.000015,0.000052,0.000268,0.000000,0.000209,0.039336,0.000039,0.000257,NaN,...,0.129391,0.111623,0.447166,0.372930,0.315618,0.499480,0.391843,0.086070,NaN,0.479341
19334,0.000185,0.000288,0.000893,0.000134,0.001483,0.000777,0.042136,0.000478,0.000700,NaN,...,0.064218,0.081233,0.046582,0.011168,0.015140,0.015904,0.012872,0.021841,NaN,0.038023

In [31]:
from sklearn.metrics import mean_squared_error

# mse =실제와 예측 점수차이 비교 
def get_mse(pred, actual):
    pred = pred[actual.nonzero()].flatten()
    actual = actual[actual.nonzero()].flatten()
    return mean_squared_error(pred,actual)

print('아이템 기반 모든 최근접 이웃 MSE:', get_mse(ga_pred, ga.values))

아이템 기반 모든 최근접 이웃 MSE: 127.00847259883234

In [32]:
def predict_ga_topsim(ga_arr, item_sim_arr, n =20):
    pred = np.zeros(ga_arr.shape)
    
    for col in range(ga_arr.shape[1]):
        top_n_items = [np.argsort(item_sim_arr[:,col])[:-n-1:-1]]
        for row in range(ga_arr.shape[0]):
            pred[row, col] = item_sim_arr[col,:][top_n_items].dot(ga_arr[row,:][top_n_items].T)
            
            pred[row, col] /= np.sum(np.abs(item_sim_arr[col,:][top_n_items]))
            
    return pred

In [ ]:

ga_pred = predict_ga_topsim(ga.values, item_sim_df.values, n=20)
print('아이템 기반 최근접 TOP-20 이웃 MSE:', get_mse(ga_pred, ga.values))

ga_pred_matrix = pd.DataFrame(data=ga_pred, index = ga.index, columns=ga.columns)

C:\Users\danie\AppData\Local\Temp/ipykernel_5744/2401581324.py:7: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  pred[row, col] = item_sim_arr[col,:][top_n_items].dot(ga_arr[row,:][top_n_items].T)
C:\Users\danie\AppData\Local\Temp/ipykernel_5744/2401581324.py:9: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  pred[row, col] /= np.sum(np.abs(item_sim_arr[col,:][top_n_items]))
C:\Users\danie\AppData\Local\Temp/ipykernel_5744/2401581324.py:9: RuntimeWarning: invalid value encountered in double_scalars
  pred[row, col] /= np.sum(np.abs(item_sim_arr[col,:][top_n_items]))

In [ ]:
ga_pred_matrix

In [ ]:
user_ga_id =ga.loc[3,:]
user_ga_id[user_ga_id > 0].sort_values(ascending=False)[:10]

In [ ]:
def get_notbuy_product(ga,고객번호):
    user_ga = ga.loc[고객번호,:]

    already_buy = user_ga[user_ga > 0].index.tolist()

    ga3_list = ga.columns.tolist()

    notbuy_list = [pro for pro in ga3_list if pro not in already_buy]
    
    return notbuy_list

In [ ]:
def recomm_pr_by_userid(pred_df,고객번호, notbuy_list, top_n=20):
    recomm_pr = pred_df.loc[고객번호,notbuy_list].sort_values(ascending=False)[:top_n]
    return recomm_pr

notbuy_list = get_notbuy_product(ga,3)

recomm_pr = recomm_pr_by_userid(ga_pred_matrix, 3, notbuy_list, top_n=20)

recomm_pr = pd.DataFrame(data=recomm_pr.values, index = recomm_pr.index,
                            columns=['pred_score'])
recomm_pr

In [ ]:
s = int(input('고객번호를 입력하세요: '))
g1_num = g1.index
g2_num = g2.index
# g3_num = g3.index
if s in g1_num:
    print('1번 군집 고객입니다.')
elif s in g2_num:
    print('2번 군집 고객입니다.')
else:
    pri
    
    
#응용구현 2 맞춤할인 검색
def recomm_pr_by_userid(pred_df,고객번호, notbuy_list, top_n=20):
    recomm_pr = pred_df.loc[고객번호,notbuy_list].sort_values(ascending=False)[:top_n]
    return recomm_pr

notbuy_list = get_notbuy_product(p,s)

recomm_pr = recomm_pr_by_userid(p_pred_matrix, s, notbuy_list, top_n=20)

recomm_pr = pd.DataFrame(data=recomm_pr.values, index = recomm_pr.index,
                            columns=['pred_score'])
display(recomm_pr)
p_T[['할인여부','할인율']]=0
sale=p_T.iloc[:,-2:]
sale.reset_index(inplace=True)
# p_T
aa=sale.sample(frac=0.2)
aa['할인여부']=1

df=pd.merge(sale,aa, on='index',how='left')
df=df[['index','할인여부_y','할인율_y']]
df.fillna(0,inplace=True)
# df['할인여부_y'].sum()
df.loc[df['할인여부_y']==1,'할인율_y']=np.random.randint(10,40,443).astype(str)
df.loc[df['할인여부_y']==1,'할인율_y']=df.loc[df['할인여부_y']==1,'할인율_y']+'%'
df[df['할인여부_y']==1]

res=pd.merge(recomm_pr.reset_index(),df[df['할인여부_y']==1], on='index',how='left').dropna()
res.columns=['품목명','평가점수','할인여부','할인율']
res2 = pd.merge(res,prod1,on='품목명',how= 'left').dropna()
res2