In [1]:
import pandas as pd
import numpy as np

In [2]:
prod = pd.read_csv('PRODCL2 (1).csv')
prod

     제휴사  대분류코드  중분류코드    소분류코드    중분류명      소분류명  상품분류 소비재분류
0      A      1    101  A010101    일용잡화      위생세제  생활잡화   편의품
1      A      1    101  A010102    일용잡화       휴지류  생활잡화   편의품
2      A      1    101  A010103    일용잡화      뷰티상품  생활잡화   편의품
3      A      1    101  A010104    일용잡화      일용잡화  생활잡화   편의품
4      A      1    101  A010105    일용잡화      세트상품  생활잡화   편의품
...   ..    ...    ...      ...     ...       ...   ...   ...
4381   D      8    802  D080204  아이메이크업     아이섀도우   화장품   편의품
4382   D      8    802  D080205  아이메이크업    메이크업세트   화장품   편의품
4383   D      8    803  D080301   립메이크업  립스틱/립라이너   화장품   편의품
4384   D      8    803  D080302   립메이크업   립글로즈/틴트   화장품   편의품
4385   D      8    804  D080401  네일메이크업  일반네일/케어류   화장품   편의품

[4386 rows x 8 columns]

In [3]:
prod1 = prod[['소분류명','소비재분류']]
prod1.columns =['품목명','소비재분류']

In [109]:
import csv
prod1.to_csv('품목소비재.csv',mode="w",encoding='euc-kr',index=False)

In [108]:
prod1

           품목명 소비재분류
0         위생세제   편의품
1          휴지류   편의품
2         뷰티상품   편의품
3         일용잡화   편의품
4         세트상품   편의품
...        ...   ...
4381     아이섀도우   편의품
4382    메이크업세트   편의품
4383  립스틱/립라이너   편의품
4384   립글로즈/틴트   편의품
4385  일반네일/케어류   편의품

[4386 rows x 2 columns]

# 여기서 g4만 추가했습니다

In [75]:
g1 = pd.read_csv('1번군집.csv',encoding='cp949')
g1 = g1.set_index('고객번호')
g2 = pd.read_csv('2번군집.csv',encoding='cp949')
g2 = g2.set_index('고객번호')
g3 = pd.read_csv('3번군집.csv',encoding='cp949')
g3 = g3.set_index('고객번호')
g4 = pd.read_csv('증가고객군집.csv',encoding='cp949')
g4 = g4.drop(['증감확인'],axis=1)
g4 = g4.set_index('고객번호')

In [76]:
prod_col1 = prod.loc[prod['소비재분류']=='편의품']['소분류명'].values
g1_col = np.array(g1.columns.to_list()) 
ili1 = np.where(np.isin(g1_col, prod_col1)==True)[0]
g1 = g1[g1_col[ili1]]
g1

,2단우산,3단우산,3분요리류,BB/파운데이션/컴팩트류,DIY소가구,DIY완구,DVD,Digital Accessory,FAST FOOD,GAP감귤,...,훼이셜스킨케어,훼이셜클렌저,훼이셜클린져,휴대폰기타용품,휴모니아,휴지류,휴지통,흑미,흑미류,흰다리새우
고객번호,,,,,,,,,,,,,,,,,,,,,
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
28,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
33,0.0,0.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
43,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19309,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
19320,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5.0
19327,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
19332,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
19333,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [105]:
import csv
ga.to_csv('전체군집.csv',mode="w",encoding='euc-kr',index=False)

In [77]:
prod_col2 = prod.loc[(prod['소비재분류']=='전문품') | (prod['소비재분류']=='선매품')]['소분류명'].values
g2_col = np.array(g2.columns.to_list()) 
ili2 = np.where(np.isin(g2_col, prod_col2)==True)[0]
g2 = g2[g2_col[ili2]]
g2

,14K,ACC Bloom (1F),ACC Bloom (3F),AK골프,ANDZ,ARCHIV,BON,Bag&Bag,DIY가전,DKNY,...,황기,황토침구,휘트니스,휠라골프,휠라아웃도어,휴고보스,휴고보스골프,히터,히터기,힐앤토트
고객번호,,,,,,,,,,,,,,,,,,,,,
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
14,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
15,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19293,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
19301,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
19310,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
19311,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
19322,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [7]:
prod_col3 = prod.loc[prod['소비재분류']=='선매품']['소분류명'].values
g3_col = np.array(g3.columns.to_list()) 
ili3 = np.where(np.isin(g3_col, prod_col3)==True)[0]
g3 = g3[g3_col[ili3]]
g3

,14K,ACC Bloom (1F),ACC Bloom (3F),AK골프,ANDZ,ARCHIV,BON,Bag&Bag,DIY가전,DKNY,...,화장품,황기,황토침구,휘트니스,휠라골프,휠라아웃도어,휴고보스,휴고보스골프,히터,히터기
고객번호,,,,,,,,,,,,,,,,,,,,,
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
17,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
18,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
19,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19298,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
19304,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
19314,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
19325,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
19334,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [78]:
g4

,14K,2단우산,3단우산,3분요리류,4대 B/D,5 ON THE GO,ACC Bloom (1F),ACC Bloom (3F),AK골프,ANDZ,...,휴대폰기타용품,휴모니아,휴지류,휴지통,흑미,흑미류,흰다리새우,히터,히터기,힐앤토트
고객번호,,,,,,,,,,,,,,,,,,,,,
6,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,2.0,0.0,0.0,1.0,0.0,0.0,0.0
7,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9,0.0,0.0,0.0,0.0,4.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19330,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0
19331,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
19335,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
19336,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0
19337,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

# g4를 합쳤습니다

In [79]:
g12 = pd.concat([g1,g2])
ga = pd.concat([g12,g3])
ga = pd.concat([ga,g4])
ga.fillna(0,inplace=True)
ga

,2단우산,3단우산,3분요리류,BB/파운데이션/컴팩트류,DIY소가구,DIY완구,DVD,Digital Accessory,FAST FOOD,GAP감귤,...,푸드코트,푸드하우스,피자레스토랑,피자헛익스프레스,한식기타,한식레스토랑,호텔,회덮밥,회전초밥,훈련
고객번호,,,,,,,,,,,,,,,,,,,,,
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
28,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
33,0.0,0.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
43,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19330,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
19331,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
19335,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,15.0,0.0,0.0,0.0,0.0,0.0
19336,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
19337,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [106]:
import csv
ga_T.to_csv('전치행렬.csv',mode="w",encoding='euc-kr',index=False)

In [80]:
# 코사인 유사도를 하기 위해서 전치 행렬을 구하는 단계 
ga_T = ga.transpose()
ga_T

고객번호,3,12,28,33,43,55,57,64,71,98,...,19318,19319,19324,19328,19329,19330,19331,19335,19336,19337
2단우산,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3단우산,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3분요리류,0.0,0.0,0.0,4.0,1.0,0.0,0.0,0.0,1.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
BB/파운데이션/컴팩트류,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
DIY소가구,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
한식레스토랑,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
호텔,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
회덮밥,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
회전초밥,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
훈련,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [81]:
from sklearn.metrics.pairwise import cosine_similarity

item_sim = cosine_similarity(ga_T,ga_T)
# 코사인 유사도 만든 행렬을 데이터프레임으로 변환 
item_sim_df = pd.DataFrame(data=item_sim, index = ga.columns,
                          columns=ga.columns)
print(item_sim_df.shape)
item_sim_df.head(3)

(3520, 3520)

,2단우산,3단우산,3분요리류,BB/파운데이션/컴팩트류,DIY소가구,DIY완구,DVD,Digital Accessory,FAST FOOD,GAP감귤,...,푸드코트,푸드하우스,피자레스토랑,피자헛익스프레스,한식기타,한식레스토랑,호텔,회덮밥,회전초밥,훈련
2단우산,1.000000,0.105851,0.009592,0.000000,0.011215,0.000000,0.000000,0.000000,0.000000,0.00000,...,0.013976,0.001427,0.000000,0.000000,0.000867,0.002714,0.000000,0.000000,0.000000,0.000000
3단우산,0.105851,1.000000,0.004153,0.010488,0.008904,0.000000,0.000000,0.000000,0.001675,0.00000,...,0.002017,0.001700,0.000000,0.000000,0.002753,0.001077,0.000000,0.020962,0.000000,0.000000
3분요리류,0.009592,0.004153,1.000000,0.010560,0.021515,0.001983,0.019032,0.041021,0.056160,0.00788,...,0.018113,0.029512,0.011751,0.026609,0.111632,0.055505,0.016155,0.025901,0.008634,0.010399

In [82]:
# 코사인유사도 내적곱한값을 코사인 유사도 절대값의 합으로 나눈 거(정규화를위해서)
import numpy as np
def predict_ga(ga_arr, item_sim_arr):
    ga_pred = ga_arr.dot(item_sim_arr)/np.array([np.abs(item_sim_arr).sum(axis=1)])
    return ga_pred

In [83]:
# 개인별 상품 예측 
ga_pred = predict_ga(ga.values, item_sim_df.values)
ga_pred_matrix = pd.DataFrame(data=ga_pred, index = ga.index,\
                            columns = ga.columns)
ga_pred_matrix

C:\Users\admin\AppData\Local\Temp/ipykernel_17624/2520657378.py:4: RuntimeWarning: invalid value encountered in true_divide
  ga_pred = ga_arr.dot(item_sim_arr)/np.array([np.abs(item_sim_arr).sum(axis=1)])

,2단우산,3단우산,3분요리류,BB/파운데이션/컴팩트류,DIY소가구,DIY완구,DVD,Digital Accessory,FAST FOOD,GAP감귤,...,푸드코트,푸드하우스,피자레스토랑,피자헛익스프레스,한식기타,한식레스토랑,호텔,회덮밥,회전초밥,훈련
고객번호,,,,,,,,,,,,,,,,,,,,,
3,1.432999,1.622357,0.265238,0.278644,0.228223,1.401304,0.123655,0.172734,0.193353,0.110683,...,0.295488,0.258159,0.179411,0.356166,0.197468,0.198643,0.613718,0.248692,0.138863,0.228429
12,0.282921,0.305087,0.302635,0.192753,0.225941,0.186593,0.186353,0.229560,0.277242,0.363957,...,0.215640,0.252366,0.234861,0.223290,0.231788,0.249693,0.167837,0.243681,0.230647,0.269138
28,0.844058,0.862197,1.171380,0.386844,0.777449,0.720919,0.671181,0.834779,0.934348,0.699016,...,0.725843,0.792951,0.784347,0.865507,0.858752,0.856212,0.729667,0.946720,0.722514,1.162823
33,1.174211,1.176602,1.780108,0.563099,1.142889,1.087579,0.940792,1.285893,1.358485,1.052764,...,1.041864,1.185836,1.266296,1.385420,1.306374,1.234592,1.092941,1.359265,1.194976,1.536468
43,0.659179,0.682238,0.954849,0.261806,0.628035,0.648178,0.545213,0.708995,0.758452,0.455694,...,0.595238,0.667702,0.641869,0.743383,0.693373,0.695547,0.562725,0.800367,0.657081,0.928996
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19330,0.690102,0.694089,1.007396,0.350295,0.746948,0.672374,0.587651,0.738400,0.848513,0.640586,...,0.767665,0.751850,0.811713,0.757432,0.798786,0.781502,0.546594,0.833060,0.753713,0.763119
19331,0.452271,0.470846,0.701684,0.206005,0.490049,0.414241,0.400347,0.517064,0.580764,0.612166,...,0.452756,0.520816,0.568571,0.551783,0.514741,0.522317,0.402535,0.575572,0.486724,0.631341
19335,0.752243,0.810254,1.081367,0.388206,0.911383,0.928314,1.128491,0.956601,1.034662,0.754590,...,0.899751,1.144216,1.128885,0.947387,1.514823,0.971609,0.662771,1.036072,0.893735,0.769459
19336,0.083413,0.058982,0.069898,0.222784,0.105361,0.067714,0.087424,0.098203,0.084339,0.175165,...,0.470228,0.077640,0.084138,0.105490,0.074873,0.104324,0.156050,0.077089,0.067584,0.032077
19337,1.954803,2.020351,0.499800,0.641001,0.332617,1.821611,0.271812,0.424815,0.393161,0.174938,...,0.461481,0.424421,0.311815,0.553075,0.408562,0.335040,0.417185,0.437103,0.284303,0.664253

In [84]:
ga_pred_matrix = ga_pred_matrix.fillna(0)

In [85]:
ga_pred_matrix

,2단우산,3단우산,3분요리류,BB/파운데이션/컴팩트류,DIY소가구,DIY완구,DVD,Digital Accessory,FAST FOOD,GAP감귤,...,푸드코트,푸드하우스,피자레스토랑,피자헛익스프레스,한식기타,한식레스토랑,호텔,회덮밥,회전초밥,훈련
고객번호,,,,,,,,,,,,,,,,,,,,,
3,1.432999,1.622357,0.265238,0.278644,0.228223,1.401304,0.123655,0.172734,0.193353,0.110683,...,0.295488,0.258159,0.179411,0.356166,0.197468,0.198643,0.613718,0.248692,0.138863,0.228429
12,0.282921,0.305087,0.302635,0.192753,0.225941,0.186593,0.186353,0.229560,0.277242,0.363957,...,0.215640,0.252366,0.234861,0.223290,0.231788,0.249693,0.167837,0.243681,0.230647,0.269138
28,0.844058,0.862197,1.171380,0.386844,0.777449,0.720919,0.671181,0.834779,0.934348,0.699016,...,0.725843,0.792951,0.784347,0.865507,0.858752,0.856212,0.729667,0.946720,0.722514,1.162823
33,1.174211,1.176602,1.780108,0.563099,1.142889,1.087579,0.940792,1.285893,1.358485,1.052764,...,1.041864,1.185836,1.266296,1.385420,1.306374,1.234592,1.092941,1.359265,1.194976,1.536468
43,0.659179,0.682238,0.954849,0.261806,0.628035,0.648178,0.545213,0.708995,0.758452,0.455694,...,0.595238,0.667702,0.641869,0.743383,0.693373,0.695547,0.562725,0.800367,0.657081,0.928996
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19330,0.690102,0.694089,1.007396,0.350295,0.746948,0.672374,0.587651,0.738400,0.848513,0.640586,...,0.767665,0.751850,0.811713,0.757432,0.798786,0.781502,0.546594,0.833060,0.753713,0.763119
19331,0.452271,0.470846,0.701684,0.206005,0.490049,0.414241,0.400347,0.517064,0.580764,0.612166,...,0.452756,0.520816,0.568571,0.551783,0.514741,0.522317,0.402535,0.575572,0.486724,0.631341
19335,0.752243,0.810254,1.081367,0.388206,0.911383,0.928314,1.128491,0.956601,1.034662,0.754590,...,0.899751,1.144216,1.128885,0.947387,1.514823,0.971609,0.662771,1.036072,0.893735,0.769459
19336,0.083413,0.058982,0.069898,0.222784,0.105361,0.067714,0.087424,0.098203,0.084339,0.175165,...,0.470228,0.077640,0.084138,0.105490,0.074873,0.104324,0.156050,0.077089,0.067584,0.032077
19337,1.954803,2.020351,0.499800,0.641001,0.332617,1.821611,0.271812,0.424815,0.393161,0.174938,...,0.461481,0.424421,0.311815,0.553075,0.408562,0.335040,0.417185,0.437103,0.284303,0.664253

In [86]:
from sklearn.metrics import mean_squared_error

# mse =실제와 예측 점수차이 비교 
def get_mse(pred, actual):
    pred = pred[actual.nonzero()].flatten()
    actual = actual[actual.nonzero()].flatten()
    return mean_squared_error(pred,actual)

print('아이템 기반 모든 최근접 이웃 MSE:', get_mse(ga_pred, ga.values))

아이템 기반 모든 최근접 이웃 MSE: 100.04315236903973

In [87]:
def predict_ga_topsim(ga_arr, item_sim_arr, n =20):
    pred = np.zeros(ga_arr.shape)
    
    for col in range(ga_arr.shape[1]):
        top_n_items = [np.argsort(item_sim_arr[:,col])[:-n-1:-1]]
        for row in range(ga_arr.shape[0]):
            pred[row, col] = item_sim_arr[col,:][top_n_items].dot(ga_arr[row,:][top_n_items].T)
            
            pred[row, col] /= np.sum(np.abs(item_sim_arr[col,:][top_n_items]))
            
    return pred

In [88]:

ga_pred = predict_ga_topsim(ga.values, item_sim_df.values, n=20)
print('아이템 기반 최근접 TOP-20 이웃 MSE:', get_mse(ga_pred, ga.values))

ga_pred_matrix = pd.DataFrame(data=ga_pred, index = ga.index, columns=ga.columns)

C:\Users\admin\AppData\Local\Temp/ipykernel_17624/2401581324.py:7: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  pred[row, col] = item_sim_arr[col,:][top_n_items].dot(ga_arr[row,:][top_n_items].T)
C:\Users\admin\AppData\Local\Temp/ipykernel_17624/2401581324.py:9: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  pred[row, col] /= np.sum(np.abs(item_sim_arr[col,:][top_n_items]))
C:\Users\admin\AppData\Local\Temp/ipykernel_17624/2401581324.py:9: RuntimeWarning: invalid value encountered in double_scalars
  pred[row, col] /= np.sum(np.abs(item_sim_arr[col,:][top_n_items]))

아이템 기반 최근접 TOP-20 이웃 MSE: 74.32672690592483

In [89]:
ga_pred_matrix

,2단우산,3단우산,3분요리류,BB/파운데이션/컴팩트류,DIY소가구,DIY완구,DVD,Digital Accessory,FAST FOOD,GAP감귤,...,푸드코트,푸드하우스,피자레스토랑,피자헛익스프레스,한식기타,한식레스토랑,호텔,회덮밥,회전초밥,훈련
고객번호,,,,,,,,,,,,,,,,,,,,,
3,2.953321,1.572339,0.000000,0.000000,0.000000,1.071560,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.028345,0.0,0.000000,0.000000,0.021938
12,0.393674,0.313277,0.523197,0.000000,0.000000,0.000000,0.000000,0.055353,0.034170,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000
28,3.261456,2.833433,4.806382,0.000000,0.000000,0.000000,0.000000,0.686548,0.344050,0.022430,...,0.000000,0.000000,0.000000,0.000000,0.033254,0.140470,0.0,0.053704,0.000000,0.279976
33,1.524533,1.881674,8.835975,0.000000,0.030078,0.225284,0.000000,0.462786,1.138042,0.043654,...,0.093878,0.055394,0.090025,0.000000,0.719816,0.189199,0.0,0.560112,0.000000,0.385965
43,0.644715,0.694234,5.431815,0.000000,0.028588,0.034283,0.000000,1.447146,0.061744,0.000000,...,0.000000,0.000000,0.000000,0.024748,0.000000,0.000000,0.0,0.000000,0.000000,0.064610
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19330,1.002752,0.967032,2.985544,0.000000,0.058589,0.024267,0.000000,0.266838,0.269825,0.000000,...,0.430358,0.115661,0.030008,0.051299,0.106175,0.155789,0.0,0.134237,0.026993,0.000000
19331,0.000000,0.073253,1.850144,0.000000,0.000000,0.000000,0.000000,0.031313,0.266524,0.000000,...,0.023571,0.000000,0.207210,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000
19335,0.610659,0.686814,2.883255,0.000000,0.541072,0.486301,1.804571,1.092733,0.441306,0.025003,...,0.085969,1.230323,3.229947,0.425570,9.406264,0.646096,0.0,0.066801,0.369537,0.020690
19336,0.000000,0.000000,0.000000,0.157785,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,3.540470,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000
19337,8.545179,7.891132,0.349452,0.000000,0.028588,1.281899,0.000000,0.035721,0.029135,0.000000,...,0.000000,0.000000,0.000000,0.024748,0.000000,0.000000,0.0,0.000000,0.000000,0.165519

In [90]:
user_ga_id =ga.loc[3,:]
user_ga_id[user_ga_id > 0].sort_values(ascending=False)[:10]

일반소주       326.0
공병/공박스     152.0
생활잡화균일가     96.0
일반우유        40.0
종량제봉투       31.0
일반두유        20.0
생수          19.0
냉장면         18.0
콜라          15.0
과일음료        14.0
Name: 3, dtype: float64

In [91]:
def get_notbuy_product(ga,고객번호):
    user_ga = ga.loc[고객번호,:]

    already_buy = user_ga[user_ga > 0].index.tolist()

    ga3_list = ga.columns.tolist()

    notbuy_list = [pro for pro in ga3_list if pro not in already_buy]
    
    return notbuy_list

In [93]:
def recomm_pr_by_userid(pred_df,고객번호, notbuy_list, top_n=20):
    recomm_pr = pred_df.loc[고객번호,notbuy_list].sort_values(ascending=False)[:top_n]
    return recomm_pr

notbuy_list = get_notbuy_product(ga,3)

recomm_pr = recomm_pr_by_userid(ga_pred_matrix, 3, notbuy_list, top_n=20)

recomm_pr = pd.DataFrame(data=recomm_pr.values, index = recomm_pr.index,
                            columns=['pred_score'])
recomm_pr

             pred_score
국산맥주          32.045921
국산담배          30.703456
칵테일소주         30.340092
수입맥주          28.927548
과실주/담금주       20.885735
세정제           16.219648
서류정리용품        15.050887
일반요구르트         9.768650
유아용물티슈         8.828233
기타포장생선         8.017798
기타온장조리         7.923874
핸드워시/손세정제      7.747187
스킨케어세트         7.723960
여행용세트          7.454540
국물용건멸치         7.346655
변기시트/커버        7.071464
기능성시리얼         6.869625
기타캠핑용품         6.862569
기타일반문구/사무용품    6.787792
아이스믹스커피        6.748759

# index만 추가했습니다

In [112]:
s = int(input('고객번호를 입력하세요: '))
g1_num = g1.index
g2_num = g2.index
g3_num = g3.index
g4_num = g4.index
if s in g1_num:
    print('1번 군집 고객입니다.')
elif s in g2_num:
    print('2번 군집 고객입니다.')
elif s in g3_num:
    print('3번 군집 고객입니다.')
else:
    print('감소고객이 아닙니다.')
    
#응용구현 2 맞춤할인 검색
def recomm_pr_by_userid(pred_df,고객번호, notbuy_list, top_n=10):
    recomm_pr = pred_df.loc[고객번호,notbuy_list].sort_values(ascending=False)[:top_n]
    return recomm_pr

notbuy_list = get_notbuy_product(ga,s)

recomm_pr = recomm_pr_by_userid(ga_pred_matrix, s, notbuy_list, top_n=20)

recomm_pr = pd.DataFrame(data=recomm_pr.values, index = recomm_pr.index,
                            columns=['pred_score'])
display(recomm_pr)
ga_T[['할인여부','할인율']]=0
sale=ga_T.iloc[:,-2:]
sale.reset_index(inplace=True)
# p_T
aa=sale.sample(frac=0.2)
aa['할인여부']=1

df=pd.merge(sale,aa, on='index',how='left')
df=df[['index','할인여부_y','할인율_y']]
df.fillna(0,inplace=True)
# df['할인여부_y'].sum()
df.loc[df['할인여부_y']==1,'할인율_y']=np.random.randint(10,40,704).astype(str)
df.loc[df['할인여부_y']==1,'할인율_y']=df.loc[df['할인여부_y']==1,'할인율_y']+'%'
df[df['할인여부_y']==1]

res=pd.merge(recomm_pr.reset_index(),df[df['할인여부_y']==1], on='index',how='left').dropna()
res.columns=['품목명','평가점수','할인여부','할인율']
res2 = pd.merge(res,prod1,on='품목명',how= 'left').dropna()
res3 = res2.drop_duplicates()
res3 = res3[['품목명','소비재분류','평가점수','할인여부','할인율']]
res3

고객번호를 입력하세요: 2
3번 군집 고객입니다.

          pred_score
계육         29.149693
가공행사       27.471949
벌크김치       26.862552
냉동식품       25.694852
친환경올가      25.327179
락앤락        23.672799
기타생선       21.991872
한과(세트행사)   21.971999
식당가 일식     21.807748
포숑         20.585775
초밥         20.444630
브랑제리       20.216059
공병         18.994149
식당가 중식     18.933470
휴지류        18.883200
곶감/송이세트    18.265567
즉석구이김류     17.978328
케익류        17.609438
한차         17.119792
에스프레소      17.095331

       품목명 소비재분류       평가점수  할인여부  할인율
0       계육   편의품  29.149693   1.0  17%
1     가공행사   편의품  27.471949   1.0  12%
2     냉동식품   편의품  25.694852   1.0  27%
3     기타생선   편의품  21.991872   1.0  32%
4       포숑   편의품  20.585775   1.0  27%
5  곶감/송이세트   편의품  18.265567   1.0  19%
6      케익류   편의품  17.609438   1.0  24%
7    에스프레소   선매품  17.095331   1.0  35%