In [21]:
import pandas as pd
import numpy as np
import csv

In [5]:
t = pd.read_csv('편의선매대분류16.csv',encoding='cp949')

In [7]:
t1 = pd.read_csv('편의선매대분류17.csv',encoding='cp949')

In [8]:
t2 = pd.read_csv('전문기타대분류16.csv',encoding='cp949')

In [9]:
t3 = pd.read_csv('전문기타대분류17.csv',encoding='cp949')

In [13]:
q = pd.merge(t, t2,on='고객번호', how='left')

In [14]:
p = pd.merge(t1, t3,on='고객번호', how='left')

In [16]:
import csv
q.to_csv('대분류17기.csv',mode="w",encoding='euc-kr',index=False)

In [15]:
import csv
p.to_csv('대분류16기.csv',mode="w",encoding='euc-kr',index=False)

In [22]:
t2 = pd.read_csv('대분류16기.csv',encoding='cp949')

In [26]:
t2.columns

Index(['고객번호', '편의품구매횟수', '편의품증감1', '편의품증감2', '편의품증감3', '편의품증감4', '편의품증감5',
       '편의품증감6', '편의품변동', '선매품구매횟수', '선매품증감1', '선매품증감2', '선매품증감3', '선매품증감4',
       '선매품증감5', '선매품증감6', '선매품변동', '전문품구매횟수', '전문품1', '전문품2', '전문품3', '전문품4',
       '전문품5', '전문품6', '전문품7', '기타구매횟수', '기타1', '기타2', '기타3', '기타4', '기타5',
       '기타6', '기타7'],
      dtype='object')

In [29]:
t2 = t2.drop(['기타7','전문품7'],axis=1)

In [31]:
t2

,고객번호,편의품구매횟수,편의품증감1,편의품증감2,편의품증감3,편의품증감4,편의품증감5,편의품증감6,편의품변동,선매품구매횟수,...,전문품4,전문품5,전문품6,기타구매횟수,기타1,기타2,기타3,기타4,기타5,기타6
0,1,691.0,2,-4,0,1,2,5,14,306.0,...,0.0,509218.0,271517.0,52.0,116561.0,58509.0,245847.0,102606.0,241686.0,118225.0
1,2,715.0,0,0,0,1,-1,2,4,262.0,...,385020.0,1561444.0,0.0,16.0,380141.0,35847.0,218618.0,0.0,34184.0,37532.0
2,3,1090.0,0,-1,1,1,0,-1,4,2.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,4,670.0,-2,4,0,-2,0,1,9,126.0,...,0.0,0.0,0.0,49.0,12793.0,89617.0,86770.0,26605.0,160907.0,148518.0
4,6,1090.0,0,-1,1,-1,5,-5,13,158.0,...,0.0,0.0,63268.0,51.0,149086.0,101257.0,99309.0,77598.0,85965.0,87932.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18873,19333,638.0,-1,3,0,-2,2,0,8,8.0,...,0.0,0.0,0.0,117.0,48612.0,140053.0,336252.0,82210.0,173346.0,176207.0
18874,19334,1987.0,-5,0,0,3,4,2,14,43.0,...,0.0,0.0,0.0,16.0,0.0,0.0,24291.0,23413.0,55018.0,27344.0
18875,19335,1399.0,-5,0,0,1,0,2,8,127.0,...,0.0,0.0,0.0,127.0,55598.0,114653.0,151057.0,71211.0,248896.0,1002633.0
18876,19336,41.0,-4,4,0,0,0,-1,9,167.0,...,168499.0,0.0,223369.0,167.0,46841.0,494754.0,709972.0,520220.0,337592.0,238596.0
18877,19337,962.0,0,-2,1,0,-1,-3,7,8.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [32]:
import csv
t2.to_csv('대분류17기.csv',mode="w",encoding='euc-kr',index=False)

In [33]:
t2.columns

Index(['고객번호', '편의품구매횟수', '편의품증감1', '편의품증감2', '편의품증감3', '편의품증감4', '편의품증감5',
       '편의품증감6', '편의품변동', '선매품구매횟수', '선매품증감1', '선매품증감2', '선매품증감3', '선매품증감4',
       '선매품증감5', '선매품증감6', '선매품변동', '전문품구매횟수', '전문품1', '전문품2', '전문품3', '전문품4',
       '전문품5', '전문품6', '기타구매횟수', '기타1', '기타2', '기타3', '기타4', '기타5', '기타6'],
      dtype='object')

In [ ]:
t2 = t2.drop(['기타7','전문품7','전문품6','기타6','선매품증감6','편의품증감6'],axis=1)

In [ ]:
import csv
t2.to_csv('대분류17기.csv',mode="w",encoding='euc-kr',index=False)

In [30]:
t2.columns

Index(['고객번호', '편의품구매횟수', '편의품증감1', '편의품증감2', '편의품증감3', '편의품증감4', '편의품증감5',
       '편의품증감6', '편의품변동', '선매품구매횟수', '선매품증감1', '선매품증감2', '선매품증감3', '선매품증감4',
       '선매품증감5', '선매품증감6', '선매품변동', '전문품구매횟수', '전문품1', '전문품2', '전문품3', '전문품4',
       '전문품5', '전문품6', '기타구매횟수', '기타1', '기타2', '기타3', '기타4', '기타5', '기타6'],
      dtype='object')

In [23]:
t3 = pd.read_csv('대분류17기.csv',encoding='cp949')

In [25]:
t3.columns

Index(['고객번호', '편의품구매횟수', '편의품증감1', '편의품증감2', '편의품증감3', '편의품증감4', '편의품증감5',
       '편의품변동', '선매품구매횟수', '선매품증감1', '선매품증감2', '선매품증감3', '선매품증감4', '선매품증감5',
       '선매품변동', '전문품구매횟수', '전문품1', '전문품2', '전문품3', '전문품4', '전문품5', '전문품6',
       '기타구매횟수', '기타1', '기타2', '기타3', '기타4', '기타5', '기타6'],
      dtype='object')

In [20]:
t3

,고객번호,편의품구매횟수,편의품증감1,편의품증감2,편의품증감3,편의품증감4,편의품증감5,편의품변동,선매품구매횟수,선매품증감1,...,전문품4,전문품5,전문품6,기타구매횟수,기타1,기타2,기타3,기타4,기타5,기타6
0,1,590.0,2,-4,0,1,2,9,268.0,0,...,0.0,509218.0,271517.0,45.0,116561.0,58509.0,245847.0,102606.0,241686.0,118225.0
1,2,635.0,0,0,0,1,-1,2,219.0,0,...,385020.0,1561444.0,0.0,12.0,380141.0,35847.0,218618.0,0.0,34184.0,37532.0
2,3,957.0,0,-1,1,1,0,3,2.0,-2,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,4,559.0,-2,4,0,-2,0,8,108.0,-2,...,0.0,0.0,0.0,38.0,12793.0,89617.0,86770.0,26605.0,160907.0,148518.0
4,5,578.0,1,4,3,-3,3,14,48.0,1,...,0.0,0.0,0.0,3.0,53729.0,2719.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18892,19333,577.0,-1,3,0,-2,2,8,8.0,2,...,0.0,0.0,0.0,106.0,48612.0,140053.0,336252.0,82210.0,173346.0,176207.0
18893,19334,1829.0,-5,0,0,3,4,12,39.0,0,...,0.0,0.0,0.0,16.0,0.0,0.0,24291.0,23413.0,55018.0,27344.0
18894,19335,1212.0,-5,0,0,1,0,6,116.0,-2,...,0.0,0.0,0.0,106.0,55598.0,114653.0,151057.0,71211.0,248896.0,1002633.0
18895,19336,40.0,-4,4,0,0,0,8,145.0,-3,...,168499.0,0.0,223369.0,151.0,46841.0,494754.0,709972.0,520220.0,337592.0,238596.0
18896,19337,743.0,0,-2,1,0,-1,4,7.0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [95]:
a = pd.read_csv('편의품테이블17기.csv',encoding='cp949')

In [96]:
p = pd.read_csv('선매품테이블17기.csv',encoding='cp949')

In [97]:
q = pd.merge(a, p,on='고객번호', how='left')

In [98]:
import csv
q.to_csv('편의선매대분류17.csv',mode="w",encoding='euc-kr',index=False)

In [18]:
b = pd.read_csv('전문품테이블17기.csv',encoding='cp949')

In [19]:
c = pd.read_csv('기타테이블17기.csv',encoding='cp949')

In [22]:
d = pd.merge(b, c,on='고객번호', how='left')

In [23]:
import csv
d.to_csv('전문기타대분류17.csv',mode="w",encoding='euc-kr',index=False)

In [82]:
e = pd.read_csv('편의품테이블16기.csv',encoding='cp949')

In [78]:
f = pd.read_csv('선매품테이블16기.csv',encoding='cp949')

In [83]:
i = pd.merge(e, f,on='고객번호', how='left')

In [85]:
import csv
i.to_csv('편의선매대분류16.csv',mode="w",encoding='euc-kr',index=False)

In [31]:
g = pd.read_csv('전문품테이블16기.csv',encoding='cp949')

In [32]:
h = pd.read_csv('기타테이블16기.csv',encoding='cp949')

In [48]:
j = pd.merge(g, h,on='고객번호', how='left')

In [61]:
import csv
j.to_csv('전문기타대분류16.csv',mode="w",encoding='euc-kr',index=False)